version: "3"
services:
  postgres:
    container_name: postgres_forms
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: forms_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: "Asia/Novosibirsk"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s